# Configurations
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
highlighter: rouge

# Permalinks
permalink:        /blog/:year/:month/:day/:title

# Setup
title:            'The Circle Brighton'
username:         'CircleBrighton'
tagline:          'The Circle Brighton'
description:      'The Circle Brighton'

# Navigation
navigation:
- text: About
  url: /about/
- text: Mind
  url: /mind/
- text: Theatre
  url: http://circleartscentre.com/

# Author Details
author:         'Parham Alvani'

# Social
social:
  - text: facebook
    link: https://facebook.com/
  - text: instagram
    link: https://www.instagram.com/

# Custom vars
version:          0.7.9
